spring.application.name=secure-vault-api

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/securevault}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:YOUR_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:YOUR_PASSWORD}min
spring.jpa.properties.hibernate.format_sql=true
